# Generated by Django 3.1.3 on 2021-03-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='Обо мне:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to='profile_pics', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия:'),
        ),
    ]
